### ISSUE TITLE
Dúvida: o que acontece após Pix ser efetuado?

### ISSUE THREAD

**Issue by dgomp** [guilhermeasn/react-qrcode-pix#3]
Olá, boa noite.

Após o Pix ser efetuado, o sistema detecta (valida), ou o QR Code continua aparecendo?

**Comment by guilhermeasn** [comment]
Bom dia!

Ele continua aparecendo póis gera apenas um qrcode estático para o recebimento do PIX.

Não tem comunicação com a sua conta bancária, então não há como o qrcode saber se você já recebeu o PIX.

Para isso acontecer é preciso a implementação em conjunto com a API do Banco Central.
