### ISSUE TITLE
Funcionalidade: Incluir campo "Mensagem" para criar códigos PIX com mensagens inclusas.

### ISSUE THREAD

**Issue by phamaralbr** [guilhermeasn/react-qrcode-pix#4]
Ao criar um QR Code de PIX com o aplicativo do Nubank, é possível incluir uma mensagem. É uma funcionalidade útil que poderia ser implementada aqui.

**Comment by guilhermeasn** [comment]
A mensagem que está dizendo é pra quem está pagando inserir no app do banco e não na implementação do qrcode.
